### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by Flourad** [swenyang/react-iscroll#2]
A page uses react-iscroll. When I enters and leaves the page frequently and quickly.Then the following errors occurred:
![image](https://cloud.githubusercontent.com/assets/1535874/19635974/cee0e2e8-99f8-11e6-8cc6-2c54f9bfe765.png)

![image](https://cloud.githubusercontent.com/assets/1535874/19635924/6eabbc86-99f8-11e6-989f-3e91faf482f4.png)

**Comment by Flourad** [comment]
Add the if statement, then no errors:

![image](https://cloud.githubusercontent.com/assets/1535874/19638638/68b6d090-9a07-11e6-919c-89a73aea45eb.png)

Because if create iScrollInstance unsuccessfully, then destroy the instance will fail.

**Comment by swenyang** [comment]
Hi, I checked my code and I've validated iscroll instance before destroying:

```
if (this._iScroll) {
    this._iScroll.destroy()
    this._iScroll = null
}
```

 So is `_teardownIScroll()` function written by you?

**Comment by Flourad** [comment]
Oh, I'm so sorry, i made a mistake, the library i used is https://github.com/schovi/react-iscroll.
But your code is extraordinary. And thank you for your answer again.

**Comment by swenyang** [comment]
Thank you, I tried [schovi](https://github.com/schovi/react-iscroll) before and found many bugs so wrote one based on need. PRs are welcomed to help improving this repo. And I'm going to close this issue.
